
export const countries = [
  { value: 'AF', label: 'أفغانستان' },
  { value: 'AL', label: 'ألبانيا' },
  { value: 'DZ', label: 'الجزائر' },
  { value: 'AS', label: 'ساموا الأمريكية' },
  { value: 'AD', label: 'أندورا' },
  { value: 'AO', label: 'أنغولا' },
  { value: 'AI', label: 'أنغيلا' },
  { value: 'AQ', label: 'القارة القطبية الجنوبية' },
  { value: 'AG', label: 'أنتيغوا وبربودا' },
  { value: 'AR', label: 'الأرجنتين' },
  { value: 'AM', label: 'أرمينيا' },
  { value: 'AW', label: 'أروبا' },
  { value: 'AU', label: 'أستراليا' },
  { value: 'AT', label: 'النمسا' },
  { value: 'AZ', label: 'أذربيجان' },
  { value: 'BS', label: 'الباهاما' },
  { value: 'BH', label: 'البحرين' },
  { value: 'BD', label: 'بنغلاديش' },
  { value: 'BB', label: 'بربادوس' },
  { value: 'BY', label: 'بيلاروس' },
  { value: 'BE', label: 'بلجيكا' },
  { value: 'BZ', label: 'بليز' },
  { value: 'BJ', label: 'بنين' },
  { value: 'BM', label: 'برمودا' },
  { value: 'BT', label: 'بوتان' },
  { value: 'BO', label: 'بوليفيا' },
  { value: 'BA', label: 'البوسنة والهرسك' },
  { value: 'BW', label: 'بوتسوانا' },
  { value: 'BV', label: 'جزيرة بوفيت' },
  { value: 'BR', label: 'البرازيل' },
  { value: 'IO', label: 'إقليم المحيط الهندي البريطاني' },
  { value: 'BN', label: 'بروناي' },
  { value: 'BG', label: 'بلغاريا' },
  { value: 'BF', label: 'بوركينا فاسو' },
  { value: 'BI', label: 'بوروندي' },
  { value: 'KH', label: 'كمبوديا' },
  { value: 'CM', label: 'الكاميرون' },
  { value: 'CA', label: 'كندا' },
  { value: 'CV', label: 'الرأس الأخضر' },
  { value: 'KY', label: 'جزر كايمان' },
  { value: 'CF', label: 'جمهورية أفريقيا الوسطى' },
  { value: 'TD', label: 'تشاد' },
  { value: 'CL', label: 'تشيلي' },
  { value: 'CN', label: 'الصين' },
  { value: 'CX', label: 'جزيرة عيد الميلاد' },
  { value: 'CC', label: 'جزر كوكوس' },
  { value: 'CO', label: 'كولومبيا' },
  { value: 'KM', label: 'جزر القمر' },
  { value: 'CG', label: 'الكونغو' },
  { value: 'CD', label: 'جمهورية الكونغو الديمقراطية' },
  { value: 'CK', label: 'جزر كوك' },
  { value: 'CR', label: 'كوستاريكا' },
  { value: 'CI', label: 'ساحل العاج' },
  { value: 'HR', label: 'كرواتيا' },
  { value: 'CU', label: 'كوبا' },
  { value: 'CY', label: 'قبرص' },
  { value: 'CZ', label: 'التشيك' },
  { value: 'DK', label: 'الدنمارك' },
  { value: 'DJ', label: 'جيبوتي' },
  { value: 'DM', label: 'دومينيكا' },
  { value: 'DO', label: 'جمهورية الدومينيكان' },
  { value: 'EC', label: 'الإكوادور' },
  { value: 'EG', label: 'مصر' },
  { value: 'SV', label: 'السلفادور' },
  { value: 'GQ', label: 'غينيا الاستوائية' },
  { value: 'ER', label: 'إريتريا' },
  { value: 'EE', label: 'إستونيا' },
  { value: 'ET', label: 'إثيوبيا' },
  { value: 'FK', label: 'جزر فوكلاند' },
  { value: 'FO', label: 'جزر فارو' },
  { value: 'FJ', label: 'فيجي' },
  { value: 'FI', label: 'فنلندا' },
  { value: 'FR', label: 'فرنسا' },
  { value: 'GF', label: 'غويانا الفرنسية' },
  { value: 'PF', label: 'بولينيزيا الفرنسية' },
  { value: 'TF', label: 'الأقاليم الجنوبية الفرنسية' },
  { value: 'GA', label: 'الغابون' },
  { value: 'GM', label: 'غامبيا' },
  { value: 'GE', label: 'جورجيا' },
  { value: 'DE', label: 'ألمانيا' },
  { value: 'GH', label: 'غانا' },
  { value: 'GI', label: 'جبل طارق' },
  { value: 'GR', label: 'اليونان' },
  { value: 'GL', label: 'جرينلاند' },
  { value: 'GD', label: 'غرينادا' },
  { value: 'GP', label: 'غوادلوب' },
  { value: 'GU', label: 'غوام' },
  { value: 'GT', label: 'غواتيمالا' },
  { value: 'GG', label: 'غيرنسي' },
  { value: 'GN', label: 'غينيا' },
  { value: 'GW', label: 'غينيا بيساو' },
  { value: 'GY', label: 'غيانا' },
  { value: 'HT', label: 'هايتي' },
  { value: 'HM', label: 'جزيرة هيرد وجزر ماكدونالد' },
  { value: 'VA', label: 'الفاتيكان' },
  { value: 'HN', label: 'هندوراس' },
  { value: 'HK', label: 'هونغ كونغ' },
  { value: 'HU', label: 'المجر' },
  { value: 'IS', label: 'أيسلندا' },
  { value: 'IN', label: 'الهند' },
  { value: 'ID', label: 'إندونيسيا' },
  { value: 'IR', label: 'إيران' },
  { value: 'IQ', label: 'العراق' },
  { value: 'IE', label: 'أيرلندا' },
  { value: 'IM', label: 'جزيرة مان' },
  { value: 'IL', label: 'إسرائيل' },
  { value: 'IT', label: 'إيطاليا' },
  { value: 'JM', label: 'جامايكا' },
  { value: 'JP', label: 'اليابان' },
  { value: 'JE', label: 'جيرزي' },
  { value: 'JO', label: 'الأردن' },
  { value: 'KZ', label: 'كازاخستان' },
  { value: 'KE', label: 'كينيا' },
  { value: 'KI', label: 'كيريباتي' },
  { value: 'KP', label: 'كوريا الشمالية' },
  { value: 'KR', label: 'كوريا الجنوبية' },
  { value: 'KW', label: 'الكويت' },
  { value: 'KG', label: 'قيرغيزستان' },
  { value: 'LA', label: 'لاوس' },
  { value: 'LV', label: 'لاتفيا' },
  { value: 'LB', label: 'لبنان' },
  { value: 'LS', label: 'ليسوتو' },
  { value: 'LR', label: 'ليبيريا' },
  { value: 'LY', label: 'ليبيا' },
  { value: 'LI', label: 'ليختنشتاين' },
  { value: 'LT', label: 'ليتوانيا' },
  { value: 'LU', label: 'لوكسمبورغ' },
  { value: 'MO', label: 'ماكاو' },
  { value: 'MK', label: 'مقدونيا الشمالية' },
  { value: 'MG', label: 'مدغشقر' },
  { value: 'MW', label: 'مالاوي' },
  { value: 'MY', label: 'ماليزيا' },
  { value: 'MV', label: 'المالديف' },
  { value: 'ML', label: 'مالي' },
  { value: 'MT', label: 'مالطا' },
  { value: 'MH', label: 'جزر مارشال' },
  { value: 'MQ', label: 'مارتينيك' },
  { value: 'MR', label: 'موريتانيا' },
  { value: 'MU', label: 'موريشيوس' },
  { value: 'YT', label: 'مايوت' },
  { value: 'MX', label: 'المكسيك' },
  { value: 'FM', label: 'ميكرونيزيا' },
  { value: 'MD', label: 'مولدوفا' },
  { value: 'MC', label: 'موناكو' },
  { value: 'MN', label: 'منغوليا' },
  { value: 'ME', label: 'الجبل الأسود' },
  { value: 'MS', label: 'مونتسرات' },
  { value: 'MA', label: 'المغرب' },
  { value: 'MZ', label: 'موزمبيق' },
  { value: 'MM', label: 'ميانمار' },
  { value: 'NA', label: 'ناميبيا' },
  { value: 'NR', label: 'ناورو' },
  { value: 'NP', label: 'نيبال' },
  { value: 'NL', label: 'هولندا' },
  { value: 'AN', label: 'الأنتيل الهولندية' },
  { value: 'NC', label: 'كاليدونيا الجديدة' },
  { value: 'NZ', label: 'نيوزيلندا' },
  { value: 'NI', label: 'نيكاراجوا' },
  { value: 'NE', label: 'النيجر' },
  { value: 'NG', label: 'نيجيريا' },
  { value: 'NU', label: 'نييوي' },
  { value: 'NF', label: 'جزيرة نورفولك' },
  { value: 'MP', label: 'جزر مريانا الشمالية' },
  { value: 'NO', label: 'النرويج' },
  { value: 'OM', label: 'عمان' },
  { value: 'PK', label: 'باكستان' },
  { value: 'PW', label: 'بالاو' },
  { value: 'PS', label: 'فلسطين' },
  { value: 'PA', label: 'بنما' },
  { value: 'PG', label: 'بابوا غينيا الجديدة' },
  { value: 'PY', label: 'باراجواي' },
  { value: 'PE', label: 'بيرو' },
  { value: 'PH', label: 'الفلبين' },
  { value: 'PN', label: 'جزر بيتكايرن' },
  { value: 'PL', label: 'بولندا' },
  { value: 'PT', label: 'البرتغال' },
  { value: 'PR', label: 'بورتوريكو' },
  { value: 'QA', label: 'قطر' },
  { value: 'RE', label: 'ريونيون' },
  { value: 'RO', label: 'رومانيا' },
  { value: 'RU', label: 'روسيا' },
  { value: 'RW', label: 'رواندا' },
  { value: 'BL', label: 'سان بارتيليمي' },
  { value: 'SH', label: 'سانت هيلينا' },
  { value: 'KN', label: 'سانت كيتس ونيفيس' },
  { value: 'LC', label: 'سانت لوسيا' },
  { value: 'MF', label: 'سان مارتن' },
  { value: 'PM', label: 'سان بيير وميكلون' },
  { value: 'VC', label: 'سانت فنسنت والغرينادين' },
  { value: 'WS', label: 'ساموا' },
  { value: 'SM', label: 'سان مارينو' },
  { value: 'ST', label: 'ساو تومي وبرينسيبي' },
  { value: 'SA', label: 'السعودية' },
  { value: 'SN', label: 'السنغال' },
  { value: 'RS', label: 'صربيا' },
  { value: 'SC', label: 'سيشل' },
  { value: 'SL', label: 'سيراليون' },
  { value: 'SG', label: 'سنغافورة' },
  { value: 'SK', label: 'سلوفاكيا' },
  { value: 'SI', label: 'سلوفينيا' },
  { value: 'SB', label: 'جزر سليمان' },
  { value: 'SO', label: 'الصومال' },
  { value: 'ZA', label: 'جنوب أفريقيا' },
  { value: 'GS', label: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية' },
  { value: 'ES', label: 'إسبانيا' },
  { value: 'LK', label: 'سريلانكا' },
  { value: 'SD', label: 'السودان' },
  { value: 'SR', label: 'سورينام' },
  { value: 'SJ', label: 'سفالبارد وجان ماين' },
  { value: 'SZ', label: 'إسواتيني' },
  { value: 'SE', label: 'السويد' },
  { value: 'CH', label: 'سويسرا' },
  { value: 'SY', label: 'سوريا' },
  { value: 'TW', label: 'تايوان' },
  { value: 'TJ', label: 'طاجيكستان' },
  { value: 'TZ', label: 'تنزانيا' },
  { value: 'TH', label: 'تايلاند' },
  { value: 'TL', label: 'تيمور الشرقية' },
  { value: 'TG', label: 'توغو' },
  { value: 'TK', label: 'توكلاو' },
  { value: 'TO', label: 'تونغا' },
  { value: 'TT', label: 'ترينيداد وتوباغو' },
  { value: 'TN', label: 'تونس' },
  { value: 'TR', label: 'تركيا' },
  { value: 'TM', label: 'تركمانستان' },
  { value: 'TC', label: 'جزر تيركس وكايكوس' },
  { value: 'TV', label: 'توفالو' },
  { value: 'UG', label: 'أوغندا' },
  { value: 'UA', label: 'أوكرانيا' },
  { value: 'AE', label: 'الإمارات' },
  { value: 'GB', label: 'المملكة المتحدة' },
  { value: 'US', label: 'الولايات المتحدة' },
  { value: 'UM', label: 'جزر الولايات المتحدة النائية الصغرى' },
  { value: 'UY', label: 'أوروجواي' },
  { value: 'UZ', label: 'أوزبكستان' },
  { value: 'VU', label: 'فانواتو' },
  { value: 'VE', label: 'فنزويلا' },
  { value: 'VN', label: 'فيتنام' },
  { value: 'VG', label: 'جزر العذراء البريطانية' },
  { value: 'VI', label: 'جزر العذراء الأمريكية' },
  { value: 'WF', label: 'واليس وفوتونا' },
  { value: 'EH', label: 'الصحراء الغربية' },
  { value: 'YE', label: 'اليمن' },
  { value: 'ZM', label: 'زامبيا' },
  { value: 'ZW', label: 'زيمبابوي' }
];

export const sectors = [
  'زراعة وأغذية',
  'تكنولوجيا ومعلومات',
  'خدمات طبية',
  'خدمات لوجستية',
  'تصنيع وإنتاج',
  'خدمات تعليمية',
  'خدمات مالية',
  'عقارات وإنشاءات',
  'أخرى'
];
