// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ioaquavsvfrwnmohyuhu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvYXF1YXZzdmZyd25tb2h5dWh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mjg4NDUsImV4cCI6MjA2NDMwNDg0NX0.kogT9IfScEdE647aW2HnoDs40_MpX2EEcIMFwjWx74o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);